services:
  - type: web
    name: campus-murense
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false          # Introduir manualment al Dashboard de Render
      - key: SECRET_KEY
        generateValue: true  # Render genera una clau aleatòria segura automàticament
      - key: ADMIN_DEFAULT_PASSWORD
        value: ClaveInicialSegura2027!
      - key: AUTO_SEED
        value: "true"
      - key: PORT
        value: "8000"
